// nextjs/src/app/en/members/Members.tsx
'use client'
import React, { useEffect, useState } from "react";
import { members } from "@/app/constants/membersData";
import MemberCard from "@/app/components/MemberCard";

const Members = () => {
  const [currentMember, setCurrentMember] = useState(members[0]);

  useEffect(() => {
    window.scrollTo(0, 1);
  }, );

  return (
    <main
      id="members"
      className="px-4 py-8 lg:px-16 lg:pb-32 pt-32 bg-black text-white gradient-sm md:gradient-md lg:gradient"
    >
      <div className="flex flex-col justify-center items-center max-container">
        <div className="pb-32">
          <h1 className="heading-text">
            Galactico
          </h1>
        </div>

        {currentMember && (
          <div className="flex w-full flex-col xl:flex-row justify-center items-start gap-16 mt-16">
            <div className="flex flex-col gap-8 flex-1 mx-auto">
              <h2 className="font-palanquin font-bold text-2xl xl:text-3xl">
                {currentMember.name}
                {currentMember.nickname_en && <span> ({currentMember.nickname_en})</span>}
              </h2>
              <div className="data flex flex-col justify-start items-start gap-4">
                <div className="flex flex-row justify-start gap-4">
                  <p className="pill">{currentMember.weight} kg</p>
                  <p className="pill">{currentMember.category}</p>
                </div>
                <div className="flex flex-row justify-start gap-3">
                  <div className="flex flex-row">
                    <img
                      className="w-8 lg:w-10 h-auto mr-2"
                      src="/icons/medal.svg"
                      alt="POWERLIFTING MEDAL ICON"
                    />
                    <p>
                      Years: {currentMember.years_competing}
                    </p>
                  </div>
                  {currentMember.records > 0 && (
                    <div className="flex flex-row">
                      <img
                        className="w-8 lg:w-10 h-auto mr-2"
                        src="/icons/trophy-yellow.svg"
                        alt="POWERLIFTING TROPHY ICON"
                      />
                      <p>Records: {currentMember.records}</p>
                    </div>
                  )}
                </div>
                <div className="flex flex-row justify-start gap-2">
                  <a href={currentMember.ig} target="_blank" rel="noreferrer">
                    <img
                      className="w-8 lg:w-10 h-auto"
                      src="/icons/ig-white.svg"
                      alt="POWERLIFTING CLUB IG"
                    />
                  </a>
                  <a href={currentMember.ipf} target="_blank" rel="noreferrer">
                    <img
                      className="w-8 lg:w-10 h-auto"
                      src="/icons/trophy.svg"
                      alt="POWERLIFTING CLUB TROPHY"
                    />
                  </a>
                </div>
                <p className="mt-4 max-w-lg" dangerouslySetInnerHTML={{ __html: currentMember.description_en }} />
              </div>
            </div>
            {currentMember.imgUrl && (
              <div className="w-full flex flex-row justify-center items-center flex-1">
                <img
                  className="object-cover w-full max-w-2xl max-h-[60vh] mx-auto rounded-md"
                  src={currentMember.imgUrl}
                  alt="Slika clana powerlifting kluba"
                  loading="lazy"
                />
              </div>
            )}
          </div>
        )}

        <div className="mt-28 grid sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-20">
          {members.map((member, index) => (
            <MemberCard
              key={index}
              imgUrl={member.imgUrl}
              name={member.name}
              isCurrent={currentMember === member}
              onClick={() => setCurrentMember(member)}
            >
            </MemberCard>
          ))}
        </div>
      </div>
    </main>
  );
};

export default Members;

// angular/src/app/view/members/members.component.ts
import { Component } from '@angular/core';
import { Athlete } from '../../models/member';
import { members } from '../../models/members_data';
import { Observable, of, Subscription } from 'rxjs';
import { TranslateService } from '@ngx-translate/core';

@Component({
  selector: 'app-members',
  templateUrl: './members.component.html',
  styleUrl: './members.component.scss'
})
export class MembersComponent {
  currentMember!: Athlete;
  allMembers: Athlete[] = members

  // changes with internationalization
  category$!: Observable<string>;
  description$!: Observable<string>;
  nickname$!: Observable<string>;

  private langChangeSubscription!: Subscription;

  constructor(private translate: TranslateService) {}

  ngOnInit(): void {
    this.currentMember = members[0]

    this.updateText(this.translate.currentLang);  // Initialize text based on the current language

    // Subscribe to language change events
    this.langChangeSubscription = this.translate.onLangChange.subscribe(event => {
      this.updateText(event.lang);  // Update text whenever the language changes
    });
  }

  ngAfterViewInit(): void {
    //Called after ngAfterContentInit when the component's view has been initialized. Applies to components only.
    //Add 'implements AfterViewInit' to the class.
    if(this.translate.currentLang)
      this.updateText(this.translate.currentLang)
    else
      this.updateText(this.translate.defaultLang)
  }

  setCurrentMember(index:number) {
    this.currentMember = members[index]
    this.updateText(this.translate.currentLang || this.translate.defaultLang)
    window.scrollTo(0,1)
  }

  private updateText(lang: string) {
    if (lang === 'en') {
      this.category$ = of(this.currentMember.category_en);
      this.description$ = of(this.currentMember.description_en)
      this.nickname$ = of(this.currentMember.nickname_en)
    } else if (lang === 'hr') {
      this.category$ = of(this.currentMember.category);
      this.description$ = of(this.currentMember.description)
      this.nickname$ = of(this.currentMember.nickname)
    }
  }





}

<!-- <div class="d-flex flex-row text-center justify-content-center  main bg-white">
  <h1 class="text-center">Galacticosi</h1>
</div> -->

<main id="members" class="px-4 py-8 lg:px-16 lg:pb-32 pt-44 bg-logo-black text-white">
  <div class="flex flex-col justify-center items-center max-container">
    <div>
      <h1 class="heading-text-lg">{{"members.h" | translate}}</h1>
    </div>

    <div *ngIf="currentMember"  class="flex w-full flex-col xl:flex-row justify-center items-start gap-16 mt-16">
      <div class="flex flex-col gap-8 flex-1">
        <h2 class="font-palanquin font-bold text-2xl xl:text-3xl">{{currentMember.name}}  <span *ngIf="currentMember.nickname ">({{nickname$ | async}})</span></h2>
        <div class="data flex flex-col justify-start items-start gap-3">
          <div class="flex flex-row justify-start gap-4">
            <p class="pill">{{currentMember.weight}} kg</p>
            <p class="pill">{{category$ | async}}</p>
          </div>
          <div class="flex flex-row justify-start gap-3">
            <div class="flex flex-row">
              <img class="icon icon--md mr-2" src="/assets/images/icons/medal.svg" alt="IKONA POWERLIFTING MEDALJE">
              <p>{{"members.years" | translate}}: {{currentMember.years_competing}} </p>
            </div>
            <div *ngIf="currentMember.records > 0" class="flex flex-row">
              <img class="icon icon--md mr-2" src="/assets/images/icons/trophy-yellow.svg" alt="IKONA POWERLIFTING TROFEJA">
              <p>{{"members.records" | translate}}: {{currentMember.records}} </p>
            </div>
          </div>
          <div class="flex flex-row justify-start gap-2">
            <a href="{{currentMember.ig}}" target="_blank"><img class="icon icon--lg sm" src="/assets/images/icons/ig-white.svg" alt="POWERLIFTING KLUB IG"></a>
            <a href="{{currentMember.ipf}}" target="_blank"><img class="icon icon--lg sm" src="/assets/images/icons/trophy.svg" alt="POWERLIFTING KLUB TROPHY"></a>
          </div>
          <p class="mt-4 max-w-lg" [innerHTML]="description$ | async"></p>
        </div>
      </div>
      <div *ngIf="currentMember.imgUrl" class="w-full flex flex-row justify-center items-center flex-1">
        <img class="object-cover w-full max-w-2xl max-h-[60vh] mx-auto rounded-md" src="{{currentMember.imgUrl}}" alt="Slika clana powerlifting kluba">
      </div>
    </div>

    <div class="mt-28 grid sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-20">
      <div *ngFor="let member of allMembers; let i = index" (click)="setCurrentMember(i)">
        <app-member-card [member]="member" [isCurrent]="currentMember == member"></app-member-card>
      </div>
    </div>
  </div>


</main>

<!-- <div class="d-flex flex-row justify-content-center flex-wrap main">

  <div class = "card">
    <img class="card-bg" src="/assets/images/members/kuzma.jpg" alt="">
    <div class="card-content">
      <h2>
        Marko Kuzmić
      </h2>
      <div class="data d-flex flex-column justify-content-start">
        <div class="d-flex flex-row justify-content-start">
          <p class="pill">83 kg</p>
          <p class="pill">Junior</p>
        </div>
        <div class="d-flex flex-row justify-content-start">
          <div class="d-flex flex-row">
            <img class="icon icon--md" src="/assets/images/icons/medal.svg" alt="MEDAL">
            <p>4 medalja</p>
          </div>
          <div class="d-flex flex-row">
            <img class="icon icon--md" src="/assets/images/icons/trophy-yellow.svg" alt="TROPHY">
            <p>8 rekorda</p>
          </div>
        </div>
        <div class="d-flex flex-row justify-content-start">
          <img class="icon icon--lg sm" src="/assets/images/icons/ig-purple.svg" alt="IG">
          <img class="icon icon--lg sm" src="/assets/images/icons/trophy-purple.svg" alt="TROPHY">
        </div>
      </div>
    </div>
  </div>

  <div class = "card">
    <img src="/assets/images/members/lokas.png" alt="">
    <div class="card-content">
      <h2>
        Ivan Lokas
      </h2>
      <div class="data d-flex flex-column justify-content-start">
        <div class="d-flex flex-row justify-content-start">
          <p class="pill">83 kg</p>
          <p class="pill">Junior</p>
        </div>
        <div class="d-flex flex-row justify-content-start">
          <div class="d-flex flex-row">
            <img class="icon icon--md" src="/assets/images/icons/medal.svg" alt="MEDAL">
            <p>4 medalja</p>
          </div>
          <div class="d-flex flex-row">
            <img class="icon icon--md" src="/assets/images/icons/trophy-yellow.svg" alt="TROPHY">
            <p>8 rekorda</p>
          </div>
        </div>
        <div class="d-flex flex-row justify-content-start">
          <img class="icon icon--lg sm" src="/assets/images/icons/ig-purple.svg" alt="IG">
          <img class="icon icon--lg sm" src="/assets/images/icons/trophy-purple.svg" alt="TROPHY">
        </div>
      </div>
      <a href="#" class="button">
        Find out more
        <span class="material-symbols-outlined">
          arrow_right_alt
        </span>
      </a>
    </div>
  </div>

</div> -->



<!-- link na openipf
ig
medalje, rekordi, kilaza, kategorija
sudac -->
