// angular/src/app/view/counter/counter.component.ts
import { AfterViewInit, Component, ElementRef, Input, OnDestroy } from '@angular/core';

@Component({
  selector: 'app-counter',
  templateUrl: './counter.component.html',
  styleUrl: './counter.component.scss'
})
export class CounterComponent implements AfterViewInit, OnDestroy{
  @Input() targetValue: number = 0; // The value x to count to
  @Input() startValue: number = 0;
  currentValue: number = 0; // The displayed counter value

  timer!: ReturnType<typeof setInterval>;

  constructor(private el: ElementRef) {}

  ngAfterViewInit() {
    let observer = new IntersectionObserver((entries, observer) => {
      entries.forEach(entry => {
        if (entry.isIntersecting) {
          this.animateValue(this.targetValue);
          observer.unobserve(entry.target); // Stop observing once animation starts
        }
      });
    }, { threshold: 0.2 }); // Adjust threshold as needed

    observer.observe(this.el.nativeElement);
  }

  animateValue(target: number, duration: number = 800) {
    const start = this.startValue;
    const end = target;
    let current = start;
    const stepTime = duration / target; // Calculate the time between steps

    this.timer = setInterval(() => {
      current += 1; // Increment the value
      this.currentValue = current; // Update the displayed value

      if (current >= end) {
        clearInterval(this.timer); // Stop the timer when the end is reached
      }
    }, stepTime);
  }

  ngOnDestroy(): void {
    clearInterval(this.timer);
  }
}

<p>{{currentValue}}</p>

// nextjs/src/app/components/Counter.tsx
'use client';
import { useEffect, useRef, useState } from 'react';

const Counter = ({ targetValue = 0, startValue = 0, duration = 1400 }) => {
  const [currentValue, setCurrentValue] = useState(startValue);
  const counterRef = useRef(null);
  const timerRef = useRef(null);

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            animateValue(targetValue, duration);
            observer.unobserve(entry.target); // Stop observing once animation starts
          }
        });
      },
      { threshold: 0.2 } // Adjust threshold as needed
    );

    if (counterRef.current) {
      observer.observe(counterRef.current);
    }

    return () => {
      if (timerRef.current) {
        clearInterval(timerRef.current);
      }
    };
  }, [targetValue, duration]);

  const animateValue = (target, duration) => {
    const start = startValue;
    const steps = Math.abs(target - start); // Total number of steps
    if (steps === 0) return; // Avoid division by zero

    const stepTime = Math.max(duration / steps, 10); // Ensure a minimum step time of 10ms
    let current = start;

    timerRef.current = setInterval(() => {
      current += (target > start ? 1 : -1); // Increment or decrement based on direction
      setCurrentValue(current);

      if ((target > start && current >= target) || (target < start && current <= target)) {
        clearInterval(timerRef.current); // Stop the timer when the target is reached
        setCurrentValue(target); // Ensure exact target value is set
      }
    }, stepTime);
  };

  return <span ref={counterRef}>{currentValue}</span>;
};

export default Counter;
