// angular/src/app/view/components/member-card/member-card.component.ts
import { Component, Input } from '@angular/core';
import { Athlete } from '../../../models/member';

@Component({
  selector: 'app-member-card',
  templateUrl: './member-card.component.html',
  styleUrl: './member-card.component.scss'
})
export class MemberCardComponent {
  @Input() member!: Athlete;
  @Input() isCurrent!: boolean;
}

<div [ngClass]="{'border-logo-yellow': isCurrent}" class="group relative border-2 bg-logo-purple rounded-md max-w-72">
  <div class="">
    <img *ngIf="member.imgUrl" class="object-cover w-full h-72" src="{{member.imgUrl}}" alt="Photo of a member">
    <img *ngIf="!member.imgUrl" class="object-contain w-full h-72 p-4" src="/assets/images/logo/plk-galacticos-logo-round.png" alt="Slika clana powerlifting kluba">
  </div>
  <h3 class="text-2xl font-semibold px-4 py-4">{{member.name}}</h3>
  <div class="absolute top-0 bg-black-op flex-row justify-center items-center w-full h-full hidden group-hover:flex active:hidden duration-500 cursor-pointer">
    <img  class="bg-logo-yellow-300 rounded-full flex justify-center items-start p-2 w-12" src="/assets/images/icons/click.svg" alt="CLICK">
  </div>
</div>

// nextjs/src/app/components/MemberCard.tsx
import React from "react";
import PropTypes from "prop-types";

const MemberCard = ({ imgUrl, name, isCurrent, onClick }) => {
  return (
    <div
      className={`group relative border-2 bg-logo-black rounded-md max-w-72 ${isCurrent ? 'border-logo-yellow' : ''}`}
      onClick={onClick}
    >
      <div>
        {imgUrl ? (
          <img
            className="object-cover w-full h-72"
            src={imgUrl}
            alt="Photo of a member"
            loading="lazy"
          />
        ) : (
          <img
            className="object-contain w-full h-72 p-4"
            src="/images/logo/plk-galacticos-logo-round.png"
            alt="Slika clana powerlifting kluba"
          />
        )}
      </div>
      <div className="flex flex-row justify-start items-center">
        <h3 className="text-lg lg:text-xl font-semibold px-4 py-4">{name}</h3>
        <img className="w-4 h-auto" src="/icons/share.svg" alt="Click"/>
      </div>
      <div className="absolute top-0 bg-black-op flex-row justify-center items-center w-full h-full hidden group-hover:flex active:hidden duration-500 cursor-pointer">
        <img
          className="bg-logo-yellow-300 rounded-full flex justify-center items-start p-2 w-12"
          src="/icons/click.svg"
          alt="CLICK"
        />
      </div>
    </div>
  );
};

MemberCard.propTypes = {
  member: PropTypes.shape({
    imgUrl: PropTypes.string,
    name: PropTypes.string.isRequired,
  }).isRequired,
  isCurrent: PropTypes.bool,
  onClick: PropTypes.func,
};

export default MemberCard;
