// angular/src/app/layout/navbar/navbar.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.scss'
})
export class NavbarComponent {
  navSlide() {
    const burger = document.querySelector(".burger");
    const navContent = document.querySelector(".nav-links-mobile");

    burger?.classList.toggle("toggle");
    navContent?.classList.toggle("toggle-nav-content");
  }
}

<header>
  <!-- <div class="w-full py-1 px-2 fixed top-0 z-20 text-logo-white bg-logo-black flex flex-row justify-center items-center">
    <div class="w-full max-w-1440 flex flex-row justify-center gap-4 md:gap-8 items-center">
      <div><app-countdown></app-countdown></div>
      <div>
        <button class="btn-primary px-3 py-1">
          Register now
        </button>
      </div>
    </div>
  </div> -->

  <nav class="navbar fixed w-full z-20 py-3 px-4 text-logo-black flex-row items-center justify-center hidden sm:flex font-semibold">
   <div class="w-full max-w-1440 flex flex-row items-center justify-between">
     <a routerLink="/">
       <div class="nav-logo">
         <img src="/assets/images/logo/plk-galacticos-logo-square.png" alt="Powerlifting Klub Galacticos logo">
       </div>
     </a>
     <div class="flex flex-row justify-center items-center gap-12">
       <div class="flex flex-row justify-center items-center gap-6">
        <div class="nav-link"><a routerLink='/'>{{"nav.home" | translate}}</a></div>
        <!-- <div class="nav-link"><a routerLink='/blog'>Blog</a></div> -->
        <!-- <div class="nav-link"><a routerLink='/about'>About</a></div> -->
        <div class="nav-link"><a routerLink='/members'>{{"nav.members" | translate}}</a></div>
       </div>
       <div class="flex flex-row justify-center items-center gap-4">
          <a href="https://www.instagram.com/plk.galacticos/" target="_blank"><img class="icon icon--lg" src="/assets/images/icons/ig-logo-black.svg" alt="INSTAGRAM"></a>
          <a href="https://www.tiktok.com/@plk.galacticos" target="_blank"><img class="icon icon--lg" src="/assets/images/icons/tt-logo-black.svg" alt="TIKTOK"></a>
          <a href="https://www.youtube.com/@PLKGalacticos" target="_blank"><img class="icon icon--lg" src="/assets/images/icons/yt-logo-black.svg" alt="YOUTUBE"></a>
       </div>

      <select aria-label="Language select" name="lang" id="lang" formControlName="siteLanguage" (change)="changeSiteLanguage($event)"
        class="bg-transparent border-transparent focus:border-transparent focus:ring-0 focus:outline-none cursor-pointer">
        <option [selected]="siteLanguage.value == 'hr'" value="hr">HR</option>
        <option [selected]="siteLanguage.value == 'en'" value="en">EN</option>
      </select>
     </div>
   </div>
  </nav>

  <nav class="navbar-mobile fixed w-full z-20 p-2 flex-row items-center justify-evenly flex sm:hidden">
    <a routerLink="/">
      <div class="nav-logo">
        <img src="/assets/images/logo/plk-galacticos-logo-square.png" alt="Powerlifting Klub Galacticos logo">
      </div>
    </a>

    <div class="flex flex-col justify-center items-center fixed w-full top-[0.4rem] z-10 mt-12 h-0 overflow-hidden bg-logo-purple text-white nav-links-mobile">
      <div class="nav-link-mobile" (click)="navSlide()"><a routerLink='/'>{{"nav.home" | translate}}</a></div>
      <!-- <div class="nav-link-mobile" (click)="navSlide()"><a routerLink='/blog'>Blog</a></div> -->
      <!-- <div class="nav-link-mobile" (click)="navSlide()"><a routerLink='/about'>About</a></div> -->
      <div class="nav-link-mobile" (click)="navSlide()"><a routerLink='/members'>{{"nav.members" | translate}}</a></div>
    </div>


    <select name="lang" id="lang" formControlName="siteLanguage" (change)="changeSiteLanguage($event)"
      class="bg-transparent text-logo-purple border-transparent focus:border-transparent focus:ring-0 focus:outline-none absolute left-4 cursor-pointer">
      <option [selected]="siteLanguage.value == 'hr'" value="hr">HR</option>
      <option [selected]="siteLanguage.value == 'en'" value="en">EN</option>
    </select>
    <div class="burger" (click)="navSlide()">
      <div class="line1"></div>
      <div class="line2"></div>
      <div class="line3"></div>
    </div>
  </nav>
</header>

// nextjs/src/app/components/Navbar.tsx
'use client';
import React, { useEffect, useState } from 'react'
import Image from 'next/image'
import instagramIcon from '../../../public/icons/ig-white.svg'
import tictocIcon from '../../../public/icons/tt-white.svg'
import youtubeIcon from '../../../public/icons/yt-white.svg'
import { useRouter } from 'next/navigation'
import { usePathname } from 'next/navigation'

const Navbar = ({t}) => {
  const [isOpen, setIsOpen] = useState(false);

  const toggleMenu = () => {
    setIsOpen(!isOpen);
  };

  t = t['nav']

  const router = useRouter();
  const pathname = usePathname()
  let firstSegment = pathname.split('/')[1];

  const [lang, setLang] = useState('hr');

  const changeLanguage = (value: string) => {
    router.push('/' + value);
  };

  const handleLanguageChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
    changeLanguage(event.target.value);
  };

  useEffect(() => {
    if (firstSegment === 'en') {
        setLang('en')
    } else {
      setLang('hr')
    }
  }, [firstSegment]);

  return (
    <header className={` bg-black text-white z-50`}>
        <nav className='fixed top-0 w-full hidden lg:block py-3 px-4 z-50 bg-black'>
            <div className='max-container flex flex-row justify-between items-center'>
                <div><a href={"/" + t['home-link']}><img className='max-w-32' src={'/images/logo/plk-galacticos-logo-bright.png'} alt={'PLK Galacticos logo'}></img></a></div>
                <div className='flex flex-row justify-center items-center gap-12'>
                    <div className='flex flex-row justify-center items-center gap-3'>
                        <a className=' hover:scale-105' href={"/" + t['home-link']}>{t['home']}</a>
                        <a className=' hover:scale-105' href={"/" + t['members-link']}>{t['members']}</a>
                        {/* <a className=' hover:scale-105' href={"/" + t['kup-link']}>{t['kup']}</a> */}
                    </div>
                    <div className='flex flex-row justify-center items-center gap-3'>
                        <a href="https://www.instagram.com/plk.galacticos/" target="_blank"><Image className='w-8 h-auto' src={instagramIcon} alt={'Instagram ikona'}></Image></a>
                        <a href="https://www.tiktok.com/@plk.galacticos" target="_blank"><Image className='w-8 h-auto' src={tictocIcon} alt={'TicToc ikona'}></Image></a>
                        <a href="https://www.youtube.com/@PLKGalacticos" target="_blank"><Image className='w-8 h-auto' src={youtubeIcon} alt={'YouTube ikona'}></Image></a>
                    </div>
                    <div>
                        <select className='bg-black cursor-pointer' value={lang} onChange={handleLanguageChange}>
                          <option className='' value="en">EN</option>
                          <option className='' value="hr">HR</option>
                        </select>
                    </div>
                </div>
            </div>
        </nav>

        <nav className={`fixed top-0 w-full block lg:hidden z-50 ${isOpen ? '' : 'pointer-events-none'}`}>
            <div className='flex flex-row justify-between items-center bg-plk-black py-2 z-50 bg-black pointer-events-auto'>
                <div className='ml-2'>
                    <select className='bg-black cursor-pointer' value={lang} onChange={handleLanguageChange}>
                      <option className='' value="en">EN</option>
                      <option className='' value="hr">HR</option>
                    </select>
                </div>
                <div><a href={"/" + t['home-link']}><Image className='max-w-32' src={'/images/logo/plk-galacticos-logo-bright.png'} alt={'PLK Galacticos logo'}></Image></a></div>
                <div className={`burger mr-2 ${isOpen ? 'toggle' : ''}`} onClick={toggleMenu}>
                  <div className="line1"></div>
                  <div className="line2"></div>
                  <div className="line3"></div>
                </div>
            </div>

            <div className={`flex flex-row justify-center items-center w-full py-12 bg-black text-white transition-all ease-in-out duration-500 ${isOpen ? 'opacity-100 z-50' : '-translate-x-[100%] opacity-0 pointer-events-none'}`}>
                <div className='flex flex-col justify-center items-center gap-3'>
                        <a className=' hover:scale-105' href={"/" + t['home-link']} onClick={toggleMenu}>{t['home']}</a>
                        <a className=' hover:scale-105' href={"/" + t['members-link']} onClick={toggleMenu}>{t['members']}</a>
                        {/* <a className=' hover:scale-105' href={"/" + t['kup-link']} onClick={toggleMenu}>{t['kup']}</a> */}
                </div>
            </div>
        </nav>
    </header>
  )
}

export default Navbar
