// nextjs/src/app/sections/Join.tsx
'use client'
import React from 'react'
import useInViewAnimation from '../hooks/useInViewAnimation';
import Swal from 'sweetalert2';

const Join = ({t}) => {
    const tSwal = t['swal']
    t = t['join']
  
  const [h1Ref, h1Animation] = useInViewAnimation({ threshold: 0.1 }, 'slide-top');
  const [h2Ref, h2Animation] = useInViewAnimation({ threshold: 0.1 }, 'slide-bottom');
  const [btnRef, btnAnimation] = useInViewAnimation({ threshold: 0.1 }, 'slide-in-elliptic-top-fwd');
  
  const showAlert = () => {
    Swal.fire({
      title: tSwal['h'],
      html: `<p class="text-left">${tSwal['p']}</p>
            <div class="mt-4 mb-4">
              <ul class="list-disc ml-5">
                <li class="text-left">${tSwal['l11']}
                  <a href="${tSwal['a']}" target="_blank" class="text-blue-500 hover:underline">
                    ${tSwal['l12']}.
                  </a>
                </li>
                <li class="text-left">${tSwal['l21']}
                  <a href="https://www.instagram.com/plk.galacticos/" target="_blank" class="text-blue-500 hover:underline">
                    Instagram.
                  </a>
                  ${tSwal['l22']}
                </li>
              </ul>
            </div>`,
        icon: "info",
        confirmButtonText: "Ide gas"
    });
  };

  return (
    <section className='flex flex-col justify-center items-center gap-12 text-center'>
        <h1 ref={h1Ref as React.RefObject<HTMLHeadingElement>} className={`slide-top-pre ${h1Animation} text-4xl lg:text-6xl font-semibold`}>{t['h1']} <span className='text-logo-yellow'>{t['h2']}</span> {t['h3']}</h1>
        <h2 ref={h2Ref as React.RefObject<HTMLHeadingElement>} className={`slide-botom-pre ${h2Animation} text-2xl lg:text-3xl font-semibold max-w-lg text-center leading-normal`}>{t['p']}</h2>
        <button ref={btnRef as React.RefObject<HTMLButtonElement>} onClick={showAlert} className={`slide-in-elliptic-top-fwd-pre ${btnAnimation} bg-logo-yellow md:text-lg btn-diagonal-swipe max-md:px-4 max-md:py-2 text-white`}>{t['btn']}</button>
    </section>
  )
}

export default Join


// <swal
// #joinSwal
// title='{{"swal.h" | translate}}'
// html='<p class="text-left">{{"swal.p" | translate}}</p>
// <div class="mt-4 mb-4">
//   <ul class="list-disc ml-5">
//     <li class="text-left">{{"swal.l11" | translate}}
//       <a href="{{"swal.a" | translate}}" target="_blank" class="text-blue-500 hover:underline">
//         {{"swal.l12" | translate}}.
//       </a>
//     </li>
//     <li class="text-left">{{"swal.l21" | translate}}
//       <a href="https://www.instagram.com/plk.galacticos/" target="_blank" class="text-blue-500 hover:underline">
//         Instagram.
//       </a>
//       {{"swal.l22" | translate}}
//     </li>
//   </ul>
// </div>'
// icon="info"
// confirmButtonText="Ide gas"
// >
// </swal>

// angular/src/app/view/sections/join/join.component.ts
import { Component, ElementRef, QueryList, ViewChildren } from '@angular/core';

@Component({
  selector: 'app-join',
  templateUrl: './join.component.html',
  styleUrl: './join.component.scss'
})
export class JoinComponent {
  isInView: boolean[] = []; // Array to store visibility for each div

  @ViewChildren('trackView') trackDivs!: QueryList<ElementRef>;

  private observer!: IntersectionObserver;

  ngOnInit(): void {
    this.initializeObserver();
  }

  initializeObserver() {
    // Initialize the IntersectionObserver with a callback
    this.observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          const index = Number(entry.target.getAttribute('data-index')); // Get the div index
          this.isInView[index] = entry.isIntersecting; // Set visibility based on intersection
        });
      },
      {
        threshold: 0.5 // Adjust this threshold as needed
      }
    );
  }

  ngAfterViewInit(): void {
    // Observe each div
    this.trackDivs.forEach((div, index) => {
      this.isInView[index] = false; // Set initial visibility to false
      div.nativeElement.setAttribute('data-index', index.toString()); // Set a unique index
      this.observer.observe(div.nativeElement);
    });
  }

  ngOnDestroy(): void {
    // Disconnect the observer on component destroy
    if (this.observer) {
      this.observer.disconnect();
    }
  }
}

<section id="join" class="padding before-opac w-full min-h-[95vh] flex flex-col justify-center items-center gap-16">
    <h2 #trackView [ngClass]="{'slide-top': isInView[0], 'slide-top-pre': !isInView[0]}" class="z-10 heading-text text-center">
      {{"join.h1" | translate}}
      <span class="text-logo-yellow">{{"join.h2" | translate}}</span>
      {{"join.h3" | translate}}
    </h2>
    <p #trackView [ngClass]="{'slide-top': isInView[1], 'slide-top-pre': !isInView[1]}" class="z-10 text-xl lg:text-3xl font-semibold font-montserrat leading-normal text-center">
      {{"join.p" | translate}}
    </p>
    <button #trackView [ngClass]="{'scale-in-center': isInView[2], 'scale-in-center-pre': !isInView[2]}"
      [swal]="joinSwal"
      class="z-10 btn-primary px-10 py-3 text-lg lg:text-2xl font-semibold">
      {{"join.btn" | translate}}
    </button>
</section>

<swal
#joinSwal
title='{{"swal.h" | translate}}'
html='<p class="text-left">{{"swal.p" | translate}}</p>
<div class="mt-4 mb-4">
  <ul class="list-disc ml-5">
    <li class="text-left">{{"swal.l11" | translate}}
      <a href="{{"swal.a" | translate}}" target="_blank" class="text-blue-500 hover:underline">
        {{"swal.l12" | translate}}.
      </a>
    </li>
    <li class="text-left">{{"swal.l21" | translate}}
      <a href="https://www.instagram.com/plk.galacticos/" target="_blank" class="text-blue-500 hover:underline">
        Instagram.
      </a>
      {{"swal.l22" | translate}}
    </li>
  </ul>
</div>'
icon="info"
confirmButtonText="Ide gas"
>
</swal>
