// nextjs/src/app/sections/FAQ.tsx
'use client';
import React, { useState, useEffect, useRef } from 'react';

const FAQ = ({ t }) => {
  t = t['faq']
  const [isActive, setIsActive] = useState(new Array(14).fill(false));
  const [isInView, setIsInView] = useState(new Array(14).fill(false));
  const [hasBeenInView, setHasBeenInView] = useState(new Array(14).fill(false));
  const divRefs = useRef([]);

  const toggleClass = (index: number) => {
    setIsActive((prev) => {
      const newState = [...prev];
      newState[index] = !newState[index];
      return newState;
    });
  };

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          const index = parseInt(entry.target.getAttribute('data-index'), 10);
          if (!hasBeenInView[index] && entry.isIntersecting) {
            setIsInView((prev) => {
              const newState = [...prev];
              newState[index] = true;
              return newState;
            });
            setHasBeenInView((prev) => {
              const newState = [...prev];
              newState[index] = true;
              return newState;
            });
          }
        });
      },
      { threshold: 0.5 }
    );

    divRefs.current.forEach((div, index) => {
      if (div) {
        div.setAttribute('data-index', index);
        observer.observe(div);
      }
    });

    return () => observer.disconnect();
  }, [hasBeenInView]);

  return (
    <section className="max-container padding max-w-6xl flex flex-col justify-start items-start gap-12">
        <h2
            // @ts-ignore
            ref={(el) => (divRefs.current[0] = el)}
            className={`heading-text text-left md:text-center w-full ${isInView[0] ? 'slide-top' : 'slide-top-pre'}`}
        >
            {t['h1']}
            <span className="text-logo-yellow">{t['h2']}</span>
            {t['h3']}
        </h2>

        <div className="w-full max-w-4xl m-auto">
            {Array.from({ length: 13 }, (_, index) => (
                <div
                    key={index + 1}
                    // @ts-ignore
                    ref={(el) => (divRefs.current[index + 1] = el)}
                    className={`mt-6 pt-4 w-full border-t-2 border-logo-white ${isInView[index + 1] ? 'slide-top' : 'slide-top-pre'}`}
                >
                    <div
                      className="flex flex-row justify-start items-center gap-4 cursor-pointer"
                      onClick={() => toggleClass(index + 1)}
                    >
                      <img
                        className={`w-4 lg:w-6 h-auto transition-all duration-300 ${isActive[index + 1] ? 'rotate-90' : ''}`}
                        src="/icons/arrow-right.svg"
                        alt="ARROW"
                      />
                      <h2 className="font-semibold text-xl">
                        {t[`q${index + 1}`]}
                      </h2>
                    </div>
                    <div className={`pt-4 pl-8 lg:pl-10 ${isActive[index + 1] ? 'active' : 'hidden'}`}>
                        <span
                          dangerouslySetInnerHTML={{
                            __html: t[`a${index + 1}`],
                          }}
                        >
                        </span>
                        {index == 12 ? 
                                                <span><a href={t['join-link']} className='text-logo-yellow cursor-pointer'>{t['a132']}</a> {t['a133']}</span>
                        
                                                : ''
                        }
                    </div>
                    
                </div>
            ))}
        </div>
    </section>
  );
};

export default FAQ;

// angular/src/app/view/sections/faq/faq.component.ts
import { Component, ElementRef, Input, QueryList, ViewChildren } from '@angular/core';

@Component({
  selector: 'app-faq',
  templateUrl: './faq.component.html',
  styleUrl: './faq.component.scss'
})
export class FaqComponent {

  isActive = [false,false,false,false,false,false,false,false,false,false,false];
  isInView: boolean[] = []; // Array to store visibility for each div

  @ViewChildren('trackView') trackDivs!: QueryList<ElementRef>;

  private observer!: IntersectionObserver;

  ngOnInit(): void {
    this.initializeObserver();
  }

  toggleClass(idx: number) {
    this.isActive[idx] = !this.isActive[idx];
  }

  initializeObserver() {
    // Initialize the IntersectionObserver with a callback
    this.observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          const index = Number(entry.target.getAttribute('data-index')); // Get the div index
          this.isInView[index] = entry.isIntersecting; // Set visibility based on intersection
        });
      },
      {
        threshold: 0.5 // Adjust this threshold as needed
      }
    );
  }

  ngAfterViewInit(): void {
    // Observe each div
    this.trackDivs.forEach((div, index) => {
      this.isInView[index] = false; // Set initial visibility to false
      div.nativeElement.setAttribute('data-index', index.toString()); // Set a unique index
      this.observer.observe(div.nativeElement);
    });
  }

  ngOnDestroy(): void {
    // Disconnect the observer on component destroy
    if (this.observer) {
      this.observer.disconnect();
    }
  }
}

<section class="max-container padding max-w-6xl flex flex-col justify-start items-start gap-12">
  <h2 #trackView [ngClass]="{'slide-top': isInView[0], 'slide-top-pre': !isInView[0]}"  class="heading-text text-left md:text-center w-full">
    {{"faq.h1" | translate}}
    <span class="text-logo-yellow">{{"faq.h2" | translate}}</span>
    {{"faq.h3" | translate}}
  </h2>

  <div class="w-full">
    <div #trackView [ngClass]="{'slide-top': isInView[1], 'slide-top-pre': !isInView[1]}" >
      <div class="flex flex-row justify-start items-center gap-4 cursor-pointer"
        (click)="toggleClass(1)">
        <img [ngClass]="{'rotate-90': isActive[1]}" class="icon icon--md" src="/assets/images/icons/arrow-right.svg" alt="ARROW">
        <h2 class="font-semibold text-2xl">{{"faq.q1" | translate}}</h2>
      </div>
      <p [class.active]="isActive[1]" class="hidden">
        {{"faq.a1" | translate}}
      </p>
    </div>


    <div #trackView [ngClass]="{'slide-top': isInView[2], 'slide-top-pre': !isInView[2]}" class="mt-6 pt-4 w-full border-t-2 border-logo-white">
      <div class="flex flex-row justify-start items-center gap-4 cursor-pointer"
        (click)="toggleClass(2)">
        <img [ngClass]="{'rotate-90': isActive[2]}" class="icon icon--md" src="/assets/images/icons/arrow-right.svg" alt="ARROW">
        <h2 class="font-semibold text-2xl">{{"faq.q2" | translate}}</h2>
      </div>
      <p [class.active]="isActive[2]" class="hidden">
        {{"faq.a2" | translate}}
      </p>
    </div>

    <div #trackView [ngClass]="{'slide-top': isInView[3], 'slide-top-pre': !isInView[3]}" class="mt-6 pt-4 w-full border-t-2 border-logo-white">
      <div class="flex flex-row justify-start items-center gap-4 cursor-pointer"
        (click)="toggleClass(3)">
        <img [ngClass]="{'rotate-90': isActive[3]}" class="icon icon--md" src="/assets/images/icons/arrow-right.svg" alt="ARROW">
        <h2 class="font-semibold text-2xl">{{"faq.q3" | translate}}</h2>
      </div>
      <p [class.active]="isActive[3]" class="hidden">
        {{"faq.a3" | translate}}
      </p>
    </div>

    <div #trackView [ngClass]="{'slide-top': isInView[4], 'slide-top-pre': !isInView[4]}" class="mt-6 pt-4 w-full border-t-2 border-logo-white">
      <div class="flex flex-row justify-start items-center gap-4 cursor-pointer"
        (click)="toggleClass(4)">
        <img [ngClass]="{'rotate-90': isActive[4]}" class="icon icon--md" src="/assets/images/icons/arrow-right.svg" alt="ARROW">
        <h2 class="font-semibold text-2xl">{{"faq.q4" | translate}}</h2>
      </div>
      <p [class.active]="isActive[4]" class="hidden">
        {{"faq.a4" | translate}}
      </p>
    </div>

     <div #trackView [ngClass]="{'slide-top': isInView[5], 'slide-top-pre': !isInView[5]}" class="mt-6 pt-4 w-full border-t-2 border-logo-white">
      <div class="flex flex-row justify-start items-center gap-4 cursor-pointer"
        (click)="toggleClass(5)">
        <img [ngClass]="{'rotate-90': isActive[5]}" class="icon icon--md" src="/assets/images/icons/arrow-right.svg" alt="ARROW">
        <h2 class="font-semibold text-2xl">{{"faq.q5" | translate}}</h2>
      </div>
      <p [class.active]="isActive[5]" class="hidden">
        {{"faq.a5" | translate}}
      </p>
    </div>

    <div #trackView [ngClass]="{'slide-top': isInView[6], 'slide-top-pre': !isInView[6]}" class="mt-6 pt-4 w-full border-t-2 border-logo-white">
      <div class="flex flex-row justify-start items-center gap-4 cursor-pointer"
        (click)="toggleClass(6)">
        <img [ngClass]="{'rotate-90': isActive[6]}" class="icon icon--md" src="/assets/images/icons/arrow-right.svg" alt="ARROW">
        <h2 class="font-semibold text-2xl">{{"faq.q6" | translate}}</h2>
      </div>
      <p [class.active]="isActive[6]" class="hidden">
        {{"faq.a6" | translate}}
      </p>
    </div>

    <div #trackView [ngClass]="{'slide-top': isInView[7], 'slide-top-pre': !isInView[7]}" class="mt-6 pt-4 w-full border-t-2 border-logo-white">
      <div class="flex flex-row justify-start items-center gap-4 cursor-pointer"
        (click)="toggleClass(7)">
        <img [ngClass]="{'rotate-90': isActive[7]}" class="icon icon--md" src="/assets/images/icons/arrow-right.svg" alt="ARROW">
        <h2 class="font-semibold text-2xl">{{"faq.q7" | translate}}</h2>
      </div>
      <p [class.active]="isActive[7]" class="hidden" [innerHTML]="'faq.a7' | translate">
      </p>
    </div>

    <div #trackView [ngClass]="{'slide-top': isInView[8], 'slide-top-pre': !isInView[8]}" class="mt-6 pt-4 w-full border-t-2 border-logo-white">
      <div class="flex flex-row justify-start items-center gap-4 cursor-pointer"
        (click)="toggleClass(8)">
        <img [ngClass]="{'rotate-90': isActive[8]}" class="icon icon--md" src="/assets/images/icons/arrow-right.svg" alt="ARROW">
        <h2 class="font-semibold text-2xl">{{"faq.q8" | translate}}</h2>
      </div>
      <p [class.active]="isActive[8]" class="hidden" [innerHTML]="'faq.a8' | translate">
      </p>
    </div>

    <div #trackView [ngClass]="{'slide-top': isInView[9], 'slide-top-pre': !isInView[9]}" class="mt-6 pt-4 w-full border-t-2 border-logo-white">
      <div class="flex flex-row justify-start items-center gap-4 cursor-pointer"
        (click)="toggleClass(9)">
        <img [ngClass]="{'rotate-90': isActive[9]}" class="icon icon--md" src="/assets/images/icons/arrow-right.svg" alt="ARROW">
        <h2 class="font-semibold text-2xl">{{"faq.q9" | translate}}</h2>
      </div>
      <p [class.active]="isActive[9]" class="hidden">
        {{"faq.a9" | translate}}
      </p>
    </div>

    <div #trackView [ngClass]="{'slide-top': isInView[10], 'slide-top-pre': !isInView[10]}" class="mt-6 pt-4 w-full border-t-2 border-logo-white">
      <div class="flex flex-row justify-start items-center gap-4 cursor-pointer"
        (click)="toggleClass(10)">
        <img [ngClass]="{'rotate-90': isActive[10]}" class="icon icon--md" src="/assets/images/icons/arrow-right.svg" alt="ARROW">
        <h2 class="font-semibold text-2xl">{{"faq.q10" | translate}}</h2>
      </div>
      <p [class.active]="isActive[10]" class="hidden">
        {{"faq.a10" | translate}}
      </p>
    </div>

    <div #trackView [ngClass]="{'slide-top': isInView[11], 'slide-top-pre': !isInView[11]}" class="mt-6 pt-4 w-full border-t-2 border-logo-white">
      <div class="flex flex-row justify-start items-center gap-4 cursor-pointer"
        (click)="toggleClass(11)">
        <img [ngClass]="{'rotate-90': isActive[11]}" class="icon icon--md" src="/assets/images/icons/arrow-right.svg" alt="ARROW">
        <h2 class="font-semibold text-2xl">{{"faq.q11" | translate}}</h2>
      </div>
      <p [class.active]="isActive[11]" class="hidden">
        {{"faq.a11" | translate}}
      </p>
    </div>

    <div #trackView [ngClass]="{'slide-top': isInView[12], 'slide-top-pre': !isInView[12]}" class="mt-6 pt-4 w-full border-t-2 border-logo-white">
      <div class="flex flex-row justify-start items-center gap-4 cursor-pointer"
        (click)="toggleClass(12)">
        <img [ngClass]="{'rotate-90': isActive[12]}" class="icon icon--md" src="/assets/images/icons/arrow-right.svg" alt="ARROW">
        <h2 class="font-semibold text-2xl">{{"faq.q12" | translate}}</h2>
      </div>
      <p [class.active]="isActive[12]" class="hidden">
        {{"faq.a12" | translate}}
      </p>
    </div>

    <div #trackView [ngClass]="{'slide-top': isInView[13], 'slide-top-pre': !isInView[13]}" class="mt-6 pt-4 w-full border-t-2 border-logo-white">
      <div class="flex flex-row justify-start items-center gap-4 cursor-pointer"
        (click)="toggleClass(13)">
        <img [ngClass]="{'rotate-90': isActive[13]}" class="icon icon--md" src="/assets/images/icons/arrow-right.svg" alt="ARROW">
        <h2 class="font-semibold text-2xl">{{"faq.q13" | translate}}</h2>
      </div>
      <p [class.active]="isActive[13]" class="hidden" [innerHTML]=''>
        {{"faq.a13" | translate}}
        <a class="text-logo-yellow" routerLink="['']" fragment="join">{{"faq.a132" | translate}}</a>
        {{"faq.a133" | translate}}
      </p>
    </div>
  </div>
</section>
