// angular/src/app/view/sections/competition/competition.component.ts
import { Component, ElementRef, QueryList, ViewChildren } from '@angular/core';

@Component({
  selector: 'app-competition',
  templateUrl: './competition.component.html',
  styleUrl: './competition.component.scss'
})
export class CompetitionComponent {
  isInView: boolean[] = []; // Array to store visibility for each div

  @ViewChildren('trackView') trackDivs!: QueryList<ElementRef>;

  private observer!: IntersectionObserver;

  ngOnInit(): void {
    this.initializeObserver();
  }

  initializeObserver() {
    // Initialize the IntersectionObserver with a callback
    this.observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          const index = Number(entry.target.getAttribute('data-index')); // Get the div index
          this.isInView[index] = entry.isIntersecting; // Set visibility based on intersection
        });
      },
      {
        threshold: 0.5 // Adjust this threshold as needed
      }
    );
  }

  ngAfterViewInit(): void {
    // Observe each div
    this.trackDivs.forEach((div, index) => {
      this.isInView[index] = false; // Set initial visibility to false
      div.nativeElement.setAttribute('data-index', index.toString()); // Set a unique index
      this.observer.observe(div.nativeElement);
    });
  }

  ngOnDestroy(): void {
    // Disconnect the observer on component destroy
    if (this.observer) {
      this.observer.disconnect();
    }
  }
}

<section id="competition" class="max-container ">


  <h2 #trackView [ngClass]="{'slide-top': isInView[0], 'slide-top-pre': !isInView[0]}" class="heading-text text-left lg:text-center">
    <span class="text-logo-yellow">Cibalae</span>
    Open
    <span class="text-logo-yellow">Kup</span>
     2025
  </h2>
  <div class="flex flex-col lg:flex-row justify-between items-start gap-4 mt-24">
    <div class="flex-1">
      <h3 #trackView [ngClass]="{'slide-right': isInView[1], 'slide-right-pre': !isInView[1]}" class="text-2xl font-semibold font-palanquin leading-3">
        {{"comp.h1" | translate}}
      </h3>
      <p #trackView [ngClass]="{'slide-top': isInView[2], 'slide-top-pre': !isInView[2]}" class="info-text font-montserrat leading-normal max-w-md mt-4 lg:mt-8">
        {{"comp.p" | translate}}
      </p>

      <div #trackView [ngClass]="{'slide-top': isInView[3], 'slide-top-pre': !isInView[3]}" class="flex flex-row justify-start items-center gap-4 flex-wrap mt-4">
        <img class="icon icon--xl" src="/assets/images/icons/germany.svg" alt="GERMANY">
        <img class="icon icon--xl" src="/assets/images/icons/france.svg" alt="FRANCE">
        <img class="icon icon--xl" src="/assets/images/icons/hungary.svg" alt="HUNGARY">
        <img class="icon icon--xl" src="/assets/images/icons/slovenia.svg" alt="SLOVENIA">
      </div>

      <div #trackView [ngClass]="{'slide-top': isInView[3], 'slide-top-pre': !isInView[3]}" class="flex flex-row justify-start items-center gap-4 flex-wrap mt-4">
        <img class="icon icon--xl" src="/assets/images/icons/serbia.svg" alt="SERBIA">
        <img class="icon icon--xl" src="/assets/images/icons/bulgaria.svg" alt="BULGARIA">
        <img class="icon icon--xl" src="/assets/images/icons/greece.svg" alt="GREECE">
        <img class="icon icon--xl" src="/assets/images/icons/croatia.svg" alt="CROATIA">
      </div>

      <a href="https://www.instagram.com/plk.galacticos/" target="_blank"
        class="">
        <button #trackView [ngClass]="{'slide-right': isInView[4], 'slide-right-pre': !isInView[4]}" class="btn-primary py-3 mt-8 icon-text-aligner min-md:my-2">
          <img class="icon icon--lg" src="/assets/images/icons/ig-white.svg" alt="INSTAGRAM">
          <p class="text-xl font-semibold">{{"comp.btn" | translate}}</p>
        </button>
      </a>
    </div>
    <div class="flex-1 w-full">
      <h3 #trackView [ngClass]="{'slide-left': isInView[5], 'slide-left-pre': !isInView[5]}" class="text-2xl font-semibold font-palanquin leading-3 mb-8 mt-24 lg:mt-0">
        {{"comp.h2" | translate}}
      </h3>
      <iframe  #trackView [ngClass]="{'scale-up-bottom': isInView[6], 'scale-up-bottom-pre': !isInView[6]}"
              src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2806.698479927844!2d18.790913875918918!3d45.294314344758305!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x475c8ae094d7cb09%3A0x2df59e6296b69211!2sElementary%20school%20Antun%20Gustav%20Matos!5e0!3m2!1sen!2shr!4v1730482835010!5m2!1sen!2shr"
              style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"
              class="rounded-md w-full h-72 md:h-96 lg:h-[450px]"
              title="Cibalae Open Kup Google Maps Location">
      </iframe>
    </div>
  </div>
</section>

// nextjs/src/app/sections/Competition.tsx
'use client';
import React from 'react'
import useInViewAnimation from '../hooks/useInViewAnimation';

const Competition = ({t}) => {
  t = t['comp']  

  const [h1Ref, h1Animation] = useInViewAnimation({ threshold: 0.1 }, 'slide-top');
  const [h2Ref, h2Animation] = useInViewAnimation({ threshold: 0.1 }, 'slide-right');
  const [h3Ref, h3Animation] = useInViewAnimation({ threshold: 0.1 }, 'slide-left');
  const [pRef, pAnimation] = useInViewAnimation({ threshold: 0.1 }, 'slide-top');
  const [img1Ref, img1Animation] = useInViewAnimation({ threshold: 0.1 }, 'slide-top');
  const [img2Ref, img2Animation] = useInViewAnimation({ threshold: 0.1 }, 'slide-top');
  const [btnRef, btnAnimation] = useInViewAnimation({ threshold: 0.1 }, 'slide-right');
  const [mapRef, mapAnimation] = useInViewAnimation({ threshold: 0.1 }, 'scale-in-center');

  return (
    <section className='relative flex flex-col justify-center items-center w-full'>
        <h1 ref={h1Ref as React.RefObject<HTMLHeadingElement>} className={`slide-top-pre ${h1Animation} heading-text mb-16`}><span className='text-logo-yellow'>Cibalae </span>Open <span className='text-logo-yellow'>Kup</span> 2025</h1>

        <div className="flex flex-col lg:flex-row justify-between items-start gap-4 mt-24 max-container z-[1]">
            <div className="flex-1 mx-auto">
              <h3 ref={h2Ref as React.RefObject<HTMLHeadingElement>} className={`slide-right-pre ${h2Animation} text-2xl lg:text-3xl font-semibold font-palanquin leading-3`}>
                {t['h1']}
              </h3>
              <p ref={pRef as React.RefObject<HTMLParagraphElement>} className={`slide-top-pre ${pAnimation} info-text font-montserrat leading-normal max-w-md mt-4 lg:mt-8`}>
                {t['p']}
              </p>

              <div ref={img1Ref  as React.RefObject<HTMLDivElement>} className={`slide-top-pre ${img1Animation} flex flex-row justify-start items-center gap-4 flex-wrap mt-4`}>
                <img className="w-14 h-auto" src="/icons/germany.svg" alt="GERMANY" />
                <img className="w-14 h-auto" src="/icons/france.svg" alt="FRANCE" />
                <img className="w-14 h-auto" src="/icons/hungary.svg" alt="HUNGARY" />
                <img className="w-14 h-auto" src="/icons/slovenia.svg" alt="SLOVENIA" />
              </div>

              <div ref={img2Ref  as React.RefObject<HTMLDivElement>} className={`slide-top-pre ${img2Animation} flex flex-row justify-start items-center gap-4 flex-wrap mt-4`}>
                <img className="w-14 h-auto" src="/icons/serbia.svg" alt="SERBIA" />
                <img className="w-14 h-auto" src="/icons/bulgaria.svg" alt="BULGARIA" />
                <img className="w-14 h-auto" src="/icons/greece.svg" alt="GREECE" />
                <img className="w-14 h-auto" src="/icons/croatia.svg" alt="CROATIA" />
              </div>

              <a href="https://www.instagram.com/plk.galacticos/" target="_blank"
                className="">
                <button ref={btnRef as React.RefObject<HTMLButtonElement>} className={`slide-right-pre ${btnAnimation} btn-primary py-3 mt-8 flex flex-row justify-center items-center gap-4 min-md:my-2`}>
                  <img className="w-6 lg:w-8 h-auto" src="/icons/ig-white.svg" alt="INSTAGRAM" />
                  <p className="text-base lg:text-lg font-semibold">{t['btn']}</p>
                </button>
              </a>
            </div>
            <div className="flex-1  max-lg:w-full">
              <h3 ref={h3Ref as React.RefObject<HTMLDivElement>} className={`slide-left-pre ${h3Animation} text-2xl lg:text-3xl font-semibold font-palanquin leading-3 mb-8 mt-24 lg:mt-0`}>
                {t['h2']}
              </h3>
              <iframe  ref={mapRef as React.RefObject<HTMLIFrameElement>} className={`scale-in-center-pre ${mapAnimation} rounded-md min-w-full h-72 md:h-96 lg:h-[450px]`}
                      src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2806.698479927844!2d18.790913875918918!3d45.294314344758305!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x475c8ae094d7cb09%3A0x2df59e6296b69211!2sElementary%20school%20Antun%20Gustav%20Matos!5e0!3m2!1sen!2shr!4v1730482835010!5m2!1sen!2shr"
                      loading="lazy" referrerPolicy="no-referrer-when-downgrade"
                      title="Cibalae Open Kup Google Maps Location">
              </iframe>
            </div>
        </div>

        <div className='border-4 border-gold rounded-md p-4 rotate-45 absolute top-1/2 left-1/2 transform -translate-x-1/2 translate-y-[25rem] lg:translate-y-72'>
            <div className='border-4 border-gold rounded-md p-4'>
                <div className='border-2 border-gold rounded-md p-4'>
                    <div className='border-2 border-gold rounded-md p-4'>
                        <div className='border-[1px] border-gold rounded-md p-4'>
                            <div className='border-[1px] border-gold rounded-md p-4 min-w-48 min-h-48'></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
  )
}

export default Competition
