// angular/src/app/view/sections/hero/hero.component.ts
import { Component, ElementRef, QueryList, ViewChildren } from '@angular/core';

declare var particlesJS: any;
declare var Swal: any;

@Component({
  selector: 'app-hero',
  templateUrl: './hero.component.html',
  styleUrl: './hero.component.scss'
})
export class HeroComponent {
  isInView: boolean[] = []; // Array to store visibility for each div

  @ViewChildren('trackView') trackDivs!: QueryList<ElementRef>;

  private observer!: IntersectionObserver;

  ngOnInit(): void {
    this.initializeObserver();
    particlesJS.load('particles-js', 'assets/particles.json', function() {
      console.log('callback - particles.js config loaded');
    });

    particlesJS.load('particles-js', '../../assets/particles.json', null);
  }

  initializeObserver() {
    // Initialize the IntersectionObserver with a callback
    this.observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          const index = Number(entry.target.getAttribute('data-index')); // Get the div index
          this.isInView[index] = entry.isIntersecting; // Set visibility based on intersection
        });
      },
      {
        threshold: 0.5 // Adjust this threshold as needed
      }
    );
  }

  ngAfterViewInit(): void {
    // Observe each div
    this.trackDivs.forEach((div, index) => {
      this.isInView[index] = false; // Set initial visibility to false
      div.nativeElement.setAttribute('data-index', index.toString()); // Set a unique index
      this.observer.observe(div.nativeElement);
    });
  }

  ngOnDestroy(): void {
    // Disconnect the observer on component destroy
    if (this.observer) {
      this.observer.disconnect();
    }
  }
}

<!-- <section id="hero" class="w-full flex flex-col justify-center h-full">
  <div class="flex flex-col justify-center items-center gap-12 lg:gap-8 text-center">
    <h1 #trackView [ngClass]="{'slide-top': isInView[0], 'slide-top-pre': !isInView[0]}" class="text-4xl lg:text-8xl max-md:pt-24 font-bold font-montserrat leading-normal slide-top">Cibalae Open Kup 2025</h1>
    <img #trackView [ngClass]="{'slide-top': isInView[1], 'slide-top-pre': !isInView[1]}" class="w-full max-w-screen-sm max-lg:max-w-80 object-contain slide-top" src="/assets/images/logo/plk-galacticos-logo-bright.png" alt="GALACTICOS LOGO">
    <h2 #trackView [ngClass]="{'slide-top': isInView[2], 'slide-top-pre': !isInView[2]}" class="text-xl lg:text-3xl text-bold max-w-screen-sm slide-top">Compete with the best and prove your strength from 7th-9th March in Vinkovci</h2>
    <button #trackView [ngClass]="{'slide-top': isInView[3], 'slide-top-pre': !isInView[3]}" class="btn-gradient text-xl lg:text-2xl px-6 py-3 slide-top">Register now</button>
  </div>
</section> -->

<section id="about" class="bg-logo-black text-white">
  <div id="particles-js" class="particles-background">
    <canvas class="particles-js-canvas-el" style="width: 100%; height: 100vh;">
    </canvas>
  </div>

  <swal
    #joinSwal
    title='{{"swal.h" | translate}}'
    html='<p class="text-left">{{"swal.p" | translate}}</p>
    <div class="mt-4 mb-4">
      <ul class="list-disc ml-5">
        <li class="text-left">{{"swal.l11" | translate}}
          <a href="{{"swal.a" | translate}}" target="_blank" class="text-blue-500 hover:underline">
            {{"swal.l12" | translate}}.
          </a>
        </li>
        <li class="text-left">{{"swal.l21" | translate}}
          <a href="https://www.instagram.com/plk.galacticos/" target="_blank" class="text-blue-500 hover:underline">
            Instagram.
          </a>
          {{"swal.l22" | translate}}
        </li>
      </ul>
    </div>'
    icon="info"
    confirmButtonText="Ide gas"
    >
  </swal>

  <section class="relative hero text-center">
    <h1 class="z-10 hero-text font-bold text-3xl lg:text-6xl text-logo-purple slide-bottom font-secondary mt-12">
      {{"Powerlifting " | uppercase}}<span class="text-logo-yellow">{{"club" | uppercase}} </span> <br class="lg:hidden"> <span class="text-4xl lg:text-6xl">GALACTICOS</span>
    </h1>
    <img class="absolute h-[60vh] lg:h-[70vh] w-auto opacity-20" src="/assets/images/logo/plk-galacticos-logo-round.png" alt="Powerlifting Klub Galacticos logo">
    <h2 class="z-10 hero-text font-bold text-2xl lg:text-4xl text-logo-purple slide-top font-secondary mt-12 italic">&bdquo;{{"hero.h" | translate | uppercase}}&#8217;&#8217;</h2>
    <button class="hero-button btn-primary bg-logo-yellow-op-8 text-logo-white text-xl lg:text-3xl font-semibold z-10 slide-in-elliptic-top-fwd px-6 py-3  mt-12 hover:text-logo-purple"
    [swal]="joinSwal">
      {{"hero.btn" | translate}}
    </button>
  </section>

  <!-- <section class="hero text-center">
    <img class="hero-logo slide-top" src="/assets/images/logo/plk-galacticos-logo.svg" alt="Powerlifting Klub Galacticos logo">
    <h1 class="hero-text font-bold text-4xl xl:text-6xl text-logo-purple slide-bottom font-secondary mt-12">&bdquo;{{"hero.h" | translate | uppercase}}&#8217;&#8217;</h1>
    <button class="hero-button btn-primary bg-logo-yellow-op-8 text-logo-white text-xl md:text-3xl font-semibold z-10 slide-in-elliptic-top-fwd px-4 py-2 lg:px-6 lg:py-3  mt-12 hover:text-logo-purple"
    [swal]="joinSwal">
      {{"hero.btn" | translate}}
    </button>
  </section> -->

  <!-- DATA -->

  <section class="max-container pr-4 bg-logo-black text-white py-8">
      <div class="flex flex-col md:flex-row justify-between flex-wrap gap-12">
          <div class="flex flex-row justify-start md:justify-center items-start gap-3 md:gap-8">
            <img class="icon w-[64px] h-[64px]" src="/assets/images/icons/trophy.svg" alt="WAREHOUSE">
            <div class="flex flex-col justify-start items-start">
              <h2 class="flex text-xl md:text-2xl -translate-y-1 md:-translate-y-2 leading-none"><app-counter [targetValue]="16" class="pr-4"></app-counter></h2>
              <h4 class="md:text-lg font-semibold -translate-y-1 md:-translate-y-2">{{"hero.data.h1" | translate}}</h4>
            </div>
          </div>

          <div class="flex flex-row justify-start md:justify-center items-start gap-3 md:gap-8">
            <img class="icon w-[64px] h-[64px]" src="/assets/images/icons/medal-white.svg" alt="OPEN ROOM">
            <div class="flex flex-col max-w-64">
              <h2 class="flex text-xl md:text-2xl -translate-y-1 md:-translate-y-2 leading-none"><app-counter [targetValue]="8" class="pr-4"></app-counter></h2>
              <h4 class="md:text-lg  font-semibold -translate-y-1 md:-translate-y-2">{{"hero.data.h2" | translate}}</h4>
            </div>
          </div>

          <div class="flex flex-row justify-start md:justify-center items-start gap-3 md:gap-8">
            <img class="icon w-[64px] h-[64px]" src="/assets/images/icons/globe.svg" alt="TRUCK">
            <div class="flex flex-col max-w-32">
              <h2 class="flex text-xl md:text-2xl -translate-y-1 md:-translate-y-2 leading-none"><app-counter [targetValue]="8"></app-counter></h2>
              <h4 class="md:text-lg  font-semibold self-start -translate-y-1 md:-translate-y-2">{{"hero.data.h3" | translate}}</h4>
            </div>
          </div>
      </div>
  </section>
</section>

// nextjs/src/app/sections/Hero.tsx
'use client';
import React from 'react'
import Swal from 'sweetalert2';

const Hero = ({t}) => {
  const tSwal = t['swal']
  t = t['hero']  

  const showAlert = () => {
      Swal.fire({
        title: tSwal['h'],
        html: `<p class="text-left">${tSwal['p']}</p>
              <div class="mt-4 mb-4">
                <ul class="list-disc ml-5">
                  <li class="text-left">${tSwal['l11']}
                    <a href="${tSwal['a']}" target="_blank" class="text-blue-500 hover:underline">
                      ${tSwal['l12']}.
                    </a>
                  </li>
                  <li class="text-left">${tSwal['l21']}
                    <a href="https://www.instagram.com/plk.galacticos/" target="_blank" class="text-blue-500 hover:underline">
                      Instagram.
                    </a>
                    ${tSwal['l22']}
                  </li>
                </ul>
              </div>`,
          icon: "info",
          confirmButtonText: "Ide gas"
      });
    };

  return (
    <section className='min-w-full min-h-[100vh] bg-blend-darken bg-black/70'>
        <img className='fixed top-0 right-0 left-0 min-w-full min-h-[100vh] -z-10 object-cover' src="/images/Walter1.jpg" alt="Cucanj" />
        
        <div className='max-container flex flex-col justify-end items-start min-h-[100vh] gap-4 px-4 pb-20 lg:pb-28'>
            <h1 className='slide-top text-3xl lg:text-4xl font-extrabold uppercase leading-none'>{t['h1']}</h1>
            <h1 className='slide-top text-3xl lg:text-4xl font-extrabold uppercase leading-3'>{t['h12']}</h1>
            <h2 className='slide-top text-xl lg:text-3xl italic max-md:pb-2 max-md:pt-4'>&bdquo;{t['h2']}&#8217;&#8217;</h2>
            <div className='flex flex-col md:flex-row justify-center items-center gap-4 md:gap-8'>
                <button onClick={showAlert} className='btn-primary max-md:w-full'>{t['btn']}</button>
                <a>
                    <button onClick={showAlert} className='btn-secondary flex flex-row justify-center items-center gap-2'>
                        <img className='w-6 h-auto' src="/icons/ig-white.svg" alt="Instagram ikona" />
                        {t['btn2']}
                    </button>
                </a>
            </div>
        </div>
    </section>
  )
}

export default Hero
